### ISSUE TITLE
As a user, I want to see which of my contacts are in my allow list and block list

### ISSUE THREAD

**Issue by danjm** [MetaMask/2023-hackathon-project#4]
The list of contacts in "Settings > Contacts" should now contact `<Tag>` components for each contact in the allowlist or blocklist.

If a contact has a `'allowList'` entry in the `tags` array in its associated `addressBook` entry, then the entry in contact list ui should have a "Allow List" tag. This should have a green background and white text.

If a contact has a `'blockList'` entry in the `tags` array in its associated `addressBook` entry, then the entry in contact list ui should have a "Block List" tag. This should have a red background and white text.

**Comment by NidhiKJha** [comment]
This one's resolved here https://github.com/MetaMask/2023-hackathon-project/pull/7
