### ISSUE TITLE
As a user, I want to filter my contact list so that I can see just the "Allow List" entries or just the "Block List" entries

### ISSUE THREAD

**Issue by danjm** [MetaMask/2023-hackathon-project#5]
At the very top of the list of addresses on the "Settings > Contacts" page, we should show three `<Tag>` components. They should have the text "Allow List", "Block List" and "All".

If the "Allow List" `<Tag>` is clicked, then the contact list should be filtered to only show entries that have `'allowList'` in the `tags` array in the associated `addressBook` entry.

If the "Block List" `<Tag>` is clicked, then the contact list should be filtered to only show entries that have `'blockList'` in the `tags` array in the associated `addressBook` entry.

If the "All" `<Tag>` is clicked, then there should be no filtering, and all contacts should be shown.

**Comment by NidhiKJha** [comment]
Closing it as  [#34](https://github.com/MetaMask/2023-hackathon-project/pull/34) is merged
